### PR TITLE
Fail action when PR is not mergeable

### PR DESCRIPTION
**Pull request by roryabraham**
Hello @pascalgn 👋 

Coming from [this comment](https://github.com/pascalgn/automerge-action/issues/122#issuecomment-995284140) – this action fails silently when the pull request fails to merge. Instead, the action should exit with a non-zero exit code so that the workflow can properly handle the failure.

This PR does that by introducing a `fail` method which uses `core.setFailed` to set an error message and `process.exit(1)` to fail the action.

The change is covered by an automated unit test.

### CODE REVIEW

**Comment by roryabraham** [comment]
The circleci failures we're seeing here seem unrelated to my changes.

**Comment by AndrewGable** [comment]
The CircleCI error seems like a known error that can be fixed via a [node option flag `--openssl-legacy-provider`](https://stackoverflow.com/a/69699772/1858217), @pascalgn would you like us to fix that error in this PR or another one?

**Comment by pascalgn** [comment]
The CircleCI error should be fixed via updating the node version, could you rebase the branch?

**Comment by roryabraham** [comment]
@pascalgn thanks for the tip, that worked! 🎉

**Comment by Austio** [comment]
@pascalgn anything that I can do to help get this over the line?

**Comment by roryabraham** [comment]
@pascalgn Friendly reminder about this PR 🙂  We use this action heavily in our CI but the fact that it fails silently is a pain point we would love to resolve.

**Comment by mbiagetti** [comment]
Hi @pascalgn Any updates/idea if this feature could be shipped? Thanks!

**Comment by pascalgn** [comment]
Thanks for the PR, it's merged now! It took some more time, because I had to put this behaviour behind a new option (MERGE_ERROR_FAIL), to not break existing workflows. Thanks! 🚀

**Pull request merged**
