### PR TITLE
Use the built docker image, so it doesn't build the docker image on every run

### PR DESCRIPTION
**Pull request by michael-bud**

### CODE REVIEW

**Comment by pascalgn** [comment]
I assume this is still a draft? Because when I try it, I get
```
##[error]'docker.pkg.github.com/pascalgn/automerge-action/automerge-action' should be either '[path]/Dockerfile' or 'docker://image[:tag]'.
```

**Comment by michael-bud** [comment]
@pascalgn Nope, just a mistake (the change is untested). Apologies, should be fixed now.

**Comment by pascalgn** [comment]
No, this still isn't working:
image

Are you aware of #24? Because I think this (still) isn't supported

**Comment by pascalgn** [comment]
I think this isn't ready yet. If you have additional input or comments, feel free to reopen!

**Pull request closed without merging**
