### PR TITLE
Add custom commit message support

### LINKED ISSUE #15: Merged commit description contains all commit description
When merging a PR and squashing all the commits, the resulting commit description contains the PR title + each commit message.

Would it be possible to add a configurable option to decide wether to keep the actual behaviour or allow, for example, only the PR title to go in the merged commit description?

This is what we often do, to keep commit description short and clear.

### PR DESCRIPTION
**Pull request by rgardner**
This change adds support for custom commit messages via the `COMMIT_MESSAGE_TEMPLATE` environment variable. See the description and example in the README for supported values.

How Verified:

* Verified in a private repo  that `automatic`, `pull-request-title`, `pull-request-description`, and `pull-request-title-and-description` work as expected
* Verified [in a public repo][invalid-message-template-check] that invalid `COMMIT_MESSAGE_TEMPLATE` values cause a failed check

Closes #15

[invalid-message-template-check]: https://github.com/rgardner/automerge-action-test/pull/7/checks?check_run_id=260163614

### CODE REVIEW

**Comment by rgardner** [comment]
Thanks for this project @pascalgn! I missed the auto-complete PR functionality that [Azure DevOps has](https://docs.microsoft.com/en-us/azure/devops/repos/git/pull-requests?view=azure-devops#complete-the-pull-request) and with this change I think `automerge-action` is now at parity. I added the `pull-request-description` option because that's what Azure DevOps does and is my use-case.

Thanks for the links in the issue description, they were super helpful.

**Comment by pascalgn** [comment]
Thanks a lot for the contribution! 👍

One minor remark: I think we should throw Error instead of NeutralExitError, as it's an actual error when the commitMessage value is unknown.

One other thing: I'm not sure how common it is, but I think it would make sense to have an option where both title and description of the PR are used as commit message, like this:

```
This first line of the commit is the PR title

These following lines come from the PR description.
Possibly more lines from the description...
Possibly more lines from the description...
```

So an option like `pull-request-title-and-description` (feel very free to come up with a better/shorter name!)

WDYT?

**Comment by rgardner** [comment]
Absolutely!

That makes sense, I've switched it to `Error`. While making that change I realized that the error wasn't propagating out of `tryMerge` due to the try/catch and that automerge would retry unnecessarily. I moved the commit message template conversion out of `tryMerge` to address those issues. See this [test PR for the failed check message](https://github.com/rgardner/automerge-action-test/pull/7/checks?check_run_id=260163614).

The `pull-request-title-and-description` functionality makes sense, especially when using `MERGE_METHOD: "merge"` (e.g. [in this test PR](https://github.com/rgardner/automerge-action-test/commit/3762e55d1f908431d65813a1d870ecd0da2a3f08)).

I renamed `COMMIT_MESSAGE` to `COMMIT_MESSAGE_TEMPLATE` because I thought it was clearer, but I realize it's longer :) Feel free to suggest other names or let me know if you want me to switch back to just `COMMIT_MESSAGE` (or we can keep `COMMIT_TEMPLATE` as the environment variable but refer to it internally as `commitMessageTemplate` for clarity.

**Comment by pascalgn** [comment]
I just merged this and released a new version. Thanks a lot for your contribution! 👍

**Comment by rgardner** [comment]
You're welcome, thanks again for this project!

**Pull request merged**
