### PR TITLE
Allow for merge attempts with `blocked` state

### LINKED ISSUE #200: ΒUG: Unable to bypass branch protection rules
I use the action as follows

```
      - name: merge the PR
        uses: pascalgn/automerge-action@v0.15.5
        env:
          MERGE_ERROR_FAIL: true
          MERGE_LABELS: "${{ env.AUTOMERGE_LABEL }}"
          MERGE_COMMIT_MESSAGE: ${{ env.MERGE_COMMIT_MESSAGE }}
          MERGE_METHOD: ${{ env.MERGE_METHOD }}
          GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"
```

My repo settings:
Screenshot 2022-10-30 at 9 18 15 PM

the `${{ secrets.GH_TOKEN }` is my PAT and I am a member of a team that can 

> dismiss pull request reviews

AND

> Allow specified actors to bypass required pull requests

However merge fails:

```
...
2022-10-30T19:15:05.307Z INFO  Current PR status: mergeable_state: blocked
2022-10-30T19:15:05.307Z ERROR PR not ready to be merged after 6 tries
```

isn't that a bug?

### PR DESCRIPTION
**Pull request by BigGillyStyle**
Fixes #200 

I understand if you decide you do not want to merge this, as this may not be want the community wants.  I did test this change on our own private repos at my company, and this works *as long as* we use a GH user account to merge that has the appropriate permissions (in our case...a "service user" that can bypass branch protection rules).

### CODE REVIEW

**Comment by SaraRavasio** [comment]
Hello @pascalgn and @BigGillyStyle! 

Are there any updates regarding this PR?
I have a case where this would really come in handy, so I wanted to know if there are any plans of merging this.

Thank you!

**Comment by BigGillyStyle** [comment]
> Hello @pascalgn and @BigGillyStyle!
> 
> Are there any updates regarding this PR? I have a case where this would really come in handy, so I wanted to know if there are any plans of merging this.
> 
> Thank you!

Hi @SaraRavasio One option for you until this PR is merged is to put the following in your Github workflow file for your merge action:
```yaml
  uses: BigGillyStyle/automerge-action@main
```

I'm not planning on publishing a separate Action on the Marketplace, but you can just refer to my fork that includes just this one change.  Just an option if you're interested, as this what we're doing at work for now.

**Comment by SaraRavasio** [comment]
> ```yaml
> BigGillyStyle/automerge-action@main
> ```

Thank you @BigGillyStyle ! I'll do that 🙏

**Comment by pascalgn** [comment]
Thanks for the PR! When there is functionality that is useful to even a few people, I'm usually happy to add it. However, especially as this functionality is maybe not useful to everyone, I would like to not have it as default.

My suggestion would be to add a new configuration option, something like **MERGE_READY_STATE**, which would default to `"clean,has_hooks,unknown,unstable"`. It could then be changed to `"clean,has_hooks,unknown,unstable,blocked"` to achieve the desired functionality.

**Comment by SaraRavasio** [comment]
> Thanks for the PR! When there is functionality that is useful to even a few people, I'm usually happy to add it. However, especially as this functionality is maybe not useful to everyone, I would like to not have it as default.
> 
> My suggestion would be to add a new configuration option, something like **MERGE_READY_STATE**, which would default to `"clean,has_hooks,unknown,unstable"`. It could then be changed to `"clean,has_hooks,unknown,unstable,blocked"` to achieve the desired functionality.

that would be great actually!

**Comment by SaraRavasio** [comment]
@BigGillyStyle somehow the action doesn't really work, I get this 
any idea? some actions are still pending, but i want to be able to force the auto merge 
image

**Comment by BigGillyStyle** [comment]
> @BigGillyStyle somehow the action doesn't really work, I get this any idea? some actions are still pending, but i want to be able to force the auto merge

@SaraRavasio We use this action daily, so I'm sure it works.  However, one thing that is key is that the user account you use to do the auto-merge needs to have the permissions to overcome your branch protection settings.  Thus, if the PR didn't pass its status checks or (as is the case for us) doesn't have the required number of approvals...we created a specific user account *that is used just for this workflow* that can overcome that issue.

**Comment by BigGillyStyle** [comment]
> Thanks for the PR! When there is functionality that is useful to even a few people, I'm usually happy to add it. However, especially as this functionality is maybe not useful to everyone, I would like to not have it as default.
> 
> My suggestion would be to add a new configuration option, something like **MERGE_READY_STATE**, which would default to `"clean,has_hooks,unknown,unstable"`. It could then be changed to `"clean,has_hooks,unknown,unstable,blocked"` to achieve the desired functionality.

@pascalgn and @SaraRavasio Let me know if this is what you were thinking: #208

**Comment by pascalgn** [comment]
I've just merged #208, so if that addresses your problem, feel free to close this PR! 🙏

**Comment by BigGillyStyle** [comment]
Thanks @pascalgn !  I'll close this PR.

**Pull request closed without merging**
