### PR TITLE
Implement the ability to auto-merge an arbitrary pull request

### PR DESCRIPTION
**Pull request by roryabraham**
### Fixed issue
Fixes https://github.com/pascalgn/automerge-action/issues/144

### Details
This pull request introduces the ability to auto-merge an arbitrary pull request specified via three optional environment variables:

- `PULL_REQUEST_NUMBER`
- `GITHUB_OWNER`
- `GITHUB_REPO`

This will enable automerge-action to be used from a workflow that executes _only_ on the `workflow_dispatch` event.

**Note:**
This is my first pull request in this repository, but I did my best to follow the code style and practices that you've established in this repo. Hopefully you find my work high-quality, but if not just let me know and I'll make whatever updates you suggest 😄 Thanks for the great work in this repo!

### CODE REVIEW

**Comment by roryabraham** [comment]
> How about instead rename PULL_REQUEST_NUMBER to simply PULL_REQUEST and then let users put either 123 (simple PR number, defaults to the repo the action is running in) or pascalgn/test/123 (full PR specified)

Yeah, that sounds reasonable to me! I will update this PR soon.

**Comment by roryabraham** [comment]
Okay, this PR is updated and ready for review 👍

**Comment by roryabraham** [comment]
@pascalgn friendly reminder that this is ready for review 🙂 Thanks!

**Comment by pascalgn** [comment]
Sorry for the delay and thanks for the PR, it's merged now! 👍

**Pull request merged**
