### PR TITLE
Add external repository support

### PR DESCRIPTION
**Pull request by mzyy94**
Add to enable automerge pull-request from forked repository.

### CODE REVIEW

**Comment by pascalgn** [comment]
Could you maybe explain the use case here a bit? For example, external contributors usually cannot assign labels to PRs anyway, so as long as no label is added, the PR will not be merged. Is that not enough?

**Comment by mzyy94** [comment]
I'm developing a project as **collaborator** and pull-request is always from forked repository in the project. Collaborators can assign labels and they will request review to other collaborators.
In this my case, I want to accept automerge from forked pull-request.

**Comment by pascalgn** [comment]
OK, understood, this sounds useful! However, would you be fine to rename it to MERGE_FORKS, as I think it better explains what this option does? 🙏

**Comment by mzyy94** [comment]
Ok, and I renamed it :)

**Comment by pascalgn** [comment]
Merged, thanks for the PR!

However, I decided to change the previous default behaviour, because IMO it doesn't make sense to prevent this by default. So you don't need to set any options to be able to merge PRs from forked repositories, just update to the latest version:

```yaml
        uses: "pascalgn/automerge-action@43fd7e11ee532218966343a262f10771b5eff978"
```

**Pull request merged**
